name: hematria-gui
version: 0.1.0.0
#synopsis:
#description:
homepage: https://davsanchez.github.io/hematria
license: BSD3
author: David Sánchez
maintainer: david.sanchez.lt@gmail.com
copyright: 2021 David Sánchez
#category:
extra-source-files:
  - README.md
data-files:
  - assets/fonts/*.ttf

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.14 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show
  - hematria

executables:
  app:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -fwarn-incomplete-patterns
      - -threaded
